[project]
name = "servoc"
version = "0.1.0"
description = "Serve ASR and TTS models at blazing speed"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "torch==2.8.0",
    "fastapi>=0.124.4",
    "pydantic>=2.12.5",
    "unicorn>=2.1.4",
    "uvicorn>=0.38.0",
    "numpy>=2.2.6",
    "transformers>=4.57.3",
    "librosa>=0.11.0",
    "python-multipart>=0.0.21",
    "openai>=2.14.0",
]

[dependency-groups]
dev = [
    "locust>=2.42.6",
]


[tool.uv.sources]
torch = [
  { index = "pytorch-cpu" },
]

[[tool.uv.index]]
name = "pytorch-cpu"
url = "https://download.pytorch.org/whl/cpu"
explicit = true
